### ISSUE TITLE
exclude some instances from coastguard's management 

### ISSUE THREAD

**Issue by wjimenez5271** [wjimenez5271/coastguard#8]
If some instances are intended to behave differently, e.g. a VPN server that is long-running while the other nodes have a lifetime of only a few hours, it's important that Coastguard doesn't take action on them. A whitelist or exclude list of instances would help with this.

**Comment by dimfeld** [comment]
Blacklist would be nice too, to include all instances except certain ones. Also make these use regex matching for extra credit :)

**Comment by dimfeld** [comment]
Help offered :) I can probably hack on this a bit tomorrow.

**Comment by dimfeld** [comment]
#12 lays the groundwork for this. There's some configuration support in there as well right now but we may want it to be set up per check or something as the config model becomes richer.

**Comment by wjimenez5271** [comment]
This is great, I think @natefaerber had an interest in this as well, so hopefully he can give it a try :-).
